#spring相关配置文件
spring:
  kafka:
    bootstrap-servers: 192.168.2.5:9092
    producer:
      retries: 0
#      batch-size: 16384
#      buffer-memory: 33554432
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: mytest1
#      enable-auto-commit: true
#      auto-offset-reset: earliest
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-commit-interval: 100
      max-poll-records: 50
  data:
    mongodb:
      uri: mongodb://192.168.2.5:27017/dxy?retryWrites=true&connectTimeoutMS=60000
      port: 27017
      username: root
      password: mongodb123

#log(使用logback)
logging:
  config: classpath:logback-spring.xml


#服务上下文和端口
server:
  servlet:
    context-path: /demo
  port: 8166

#日志级别

#自定义配置
custom:
  device-kafka-topic: test
  base-url: http://localhost:8166/demo/device/save
  mongo-batch-save-size: 1000